### ISSUE TITLE
.nomedia

### ISSUE THREAD

**Issue by srt10coupe** [libasys/gallerydeluxe#3]
gallery deluxe ignore .nomedia files.

**Comment by libasys** [comment]
yes that is the correct behaviour!

**Comment by srt10coupe** [comment]
thanks for the reply, there is another way folders to hide / hide images?

 :dollar: bucks

**Comment by libasys** [comment]
the gallery app shows only folders, which have a file named "cover.jpg" all other folder without a cover.jpg file will not shown up in the gallery!

**Comment by srt10coupe** [comment]
if I delete the cover.jpg or rename then this folder should no longer be visible?

Folder in which no cover.jpg. I must be a real image or create a file as a .nomedia?

**Comment by libasys** [comment]
you can upload a image with name cover.jpg, or you rename an existing image to cover.jpg, this image is used in the album view (start screen of gallery deluxe)

**Comment by srt10coupe** [comment]
thank you, this way is better than .nomedia.

where can I :gift: a few :dollar: ?
